export const sampleProducts = [
  {
    name: "Rose Elegance",
    price: 89.0,
    category: "Floral",
    description: "Soft rose petals wrapped in vanilla and amber for a refined signature scent.",
    image: "https://images.unsplash.com/photo-1512058564366-c9e3ee8bd22e?auto=format&fit=crop&w=800&q=80",
    stock: 20,
  },
  {
    name: "Midnight Oud",
    price: 120.0,
    category: "Woody",
    description: "Deep agarwood with oud, leather, and spice for a powerful night aura.",
    image: "https://images.unsplash.com/photo-1593151553788-d8502de23b10?auto=format&fit=crop&w=800&q=80",
    stock: 15,
  },
  {
    name: "Vanilla Bloom",
    price: 75.0,
    category: "Gourmand",
    description: "Creamy vanilla and jasmine for a warm, welcoming complexity.",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    stock: 30,
  },
  {
    name: "Ocean Mist",
    price: 82.0,
    category: "Fresh",
    description: "Crisp marine notes with a touch of sea salt and musk, ideal for daily luxury.",
    image: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=800&q=80",
    stock: 25,
  },
  {
    name: "Original Rasasi Eclat d'Or",
    price: 950.0,
    category: "Oriental Floral",
    description: "A luxurious blend of bergamot, rose, jasmine, ylang-ylang, amber, musk, and vanilla for an elegant and sophisticated scent.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80",
    stock: 10,
  },
  {
    name: "Original RAEES Arabiyat Prestige",
    price: 599.0,
    category: "Floral Oriental",
    description: "An exquisite floral oriental fragrance featuring bergamot, lemon, rose, jasmine, patchouli, amber, musk, and vanilla.",
    image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?auto=format&fit=crop&w=800&q=80",
    stock: 15,
  },
  {
    name: "Original Royal Blend Bourbon",
    price: 599.0,
    category: "Gourmand",
    description: "A rich and warm gourmand scent with bourbon vanilla, spices, and amber for a regal and indulgent experience.",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80",
    stock: 12,
  },
  {
    name: "Original Hawas Black",
    price: 950.0,
    category: "Woody Oriental",
    description: "A bold woody oriental perfume with lemon, bergamot, pineapple, rose, jasmine, geranium, amber, musk, and patchouli.",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80",
    stock: 8,
  },
  {
    name: "Original Ripple Blackcurrant Arabiyat Prestige",
    price: 699.0,
    category: "Fruity Floral",
    description: "A vibrant fruity floral scent combining blackcurrant, lemon, bergamot, rose, jasmine, patchouli, amber, musk, and vanilla.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80",
    stock: 10,
  }
];
